# Generated by Django 6.0.5 on 2026-05-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desktop_automation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesktopWorkerHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_id', models.CharField(max_length=120, unique=True)),
                ('status', models.CharField(db_index=True, default='unknown', max_length=40)),
                ('current_job_id', models.PositiveIntegerField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(db_index=True)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['worker_id'],
            },
        ),
    ]
