# Generated by Django 6.0.5 on 2026-05-11 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('display_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='StudyFieldCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('display_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('iso2', models.CharField(blank=True, db_index=True, max_length=2)),
                ('iso3', models.CharField(blank=True, max_length=3)),
                ('calling_code', models.CharField(blank=True, max_length=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='countries', to='reference_data.region')),
            ],
            options={
                'ordering': ('region__display_order', 'display_order', 'name'),
                'indexes': [models.Index(fields=['region', 'is_active'], name='reference_d_region__f3c0a7_idx'), models.Index(fields=['is_active', 'display_order'], name='reference_d_is_acti_0a0af3_idx'), models.Index(fields=['slug'], name='reference_d_slug_47e182_idx'), models.Index(fields=['iso2'], name='reference_d_iso2_e2135f_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudyField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='study_fields', to='reference_data.studyfieldcategory')),
            ],
            options={
                'ordering': ('category__display_order', 'display_order', 'name'),
                'indexes': [models.Index(fields=['category', 'is_active'], name='reference_d_categor_a1b1a5_idx'), models.Index(fields=['is_active', 'display_order'], name='reference_d_is_acti_d188c6_idx'), models.Index(fields=['slug'], name='reference_d_slug_970fd0_idx')],
            },
        ),
    ]
