# Generated by Django 6.0.5 on 2026-05-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('region', models.CharField(choices=[('Asia', 'Asia'), ('Europe', 'Europe'), ('Middle East', 'Middle East'), ('Africa', 'Africa'), ('North America', 'North America'), ('Latin America', 'Latin America'), ('Oceania', 'Oceania'), ('Other', 'Other')], db_index=True, max_length=40)),
                ('iso2', models.CharField(blank=True, db_index=True, max_length=2)),
                ('iso3', models.CharField(blank=True, max_length=3)),
                ('calling_code', models.CharField(blank=True, max_length=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('region', 'display_order', 'name'),
                'indexes': [models.Index(fields=['region', 'is_active'], name='reference_d_region_8570f5_idx'), models.Index(fields=['is_active', 'display_order'], name='reference_d_is_acti_0a0af3_idx'), models.Index(fields=['slug'], name='reference_d_slug_47e182_idx')],
            },
        ),
    ]
