# Generated by Django 6.0.5 on 2026-05-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('category', models.CharField(choices=[('Computer Science & IT', 'Computer Science & IT'), ('Engineering', 'Engineering'), ('Medical & Health Sciences', 'Medical & Health Sciences'), ('Business & Economics', 'Business & Economics'), ('Social Sciences', 'Social Sciences'), ('Natural Sciences', 'Natural Sciences'), ('Agriculture & Environment', 'Agriculture & Environment'), ('Arts & Humanities', 'Arts & Humanities'), ('Education', 'Education'), ('Law & Public Policy', 'Law & Public Policy'), ('Other', 'Other')], db_index=True, max_length=80)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('category', 'display_order', 'name'),
                'indexes': [models.Index(fields=['category', 'is_active'], name='reference_d_categor_020a2a_idx'), models.Index(fields=['is_active', 'display_order'], name='reference_d_is_acti_d188c6_idx'), models.Index(fields=['slug'], name='reference_d_slug_970fd0_idx')],
            },
        ),
    ]
