# Generated by Django 6.0.5 on 2026-05-11 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_studentprofile_ai_autofill_reviewed_and_more'),
        ('reference_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='current_country',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='current_field_of_study',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='supervisor_country',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='target_countries',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='target_fields',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='current_country_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_country_profiles', to='reference_data.country'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='current_study_field_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_field_profiles', to='reference_data.studyfield'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='custom_current_study_field',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='custom_supervisor_country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='custom_target_study_fields',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='nationality_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nationality_profiles', to='reference_data.country'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='supervisor_country_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supervisor_country_profiles', to='reference_data.country'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='target_country_refs',
            field=models.ManyToManyField(blank=True, related_name='target_country_profiles', to='reference_data.country'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='target_study_field_refs',
            field=models.ManyToManyField(blank=True, related_name='target_field_profiles', to='reference_data.studyfield'),
        ),
    ]
