# Generated by Django 6.0.5 on 2026-05-12 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_email_verification_sent_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verification_nonce",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
    ]
