export type ReadinessLevel = "Low" | "Medium" | "High";

export type ProfileCompletion = {
  completion_percentage: number;
  scholarship_readiness_score: number;
  readiness_level: ReadinessLevel;
  missing_profile_fields: string[];
  missing_core_documents: string[];
};

type NullableInput = string | number | null;

export type StudentProfilePayload = {
  phone_number: string;
  whatsapp_number: string;
  date_of_birth: string | null;
  nationality: string;
  current_country: string;
  city: string;
  province: string;
  domicile: string;
  current_education_level: string;
  current_institution: string;
  current_field_of_study: string;
  graduation_year: NullableInput;
  result_status: string;
  grading_system: string;
  cgpa: NullableInput;
  percentage: NullableInput;
  division: string;
  target_degree_level: string;
  target_fields: string[];
  target_countries: string[];
  preferred_intake: string;
  study_mode_preference: string;
  funding_preference: string;
  application_fee_preference: string;
  language_instruction_preference: string;
  has_ielts: boolean;
  ielts_score: NullableInput;
  has_toefl: boolean;
  toefl_score: NullableInput;
  has_duolingo: boolean;
  duolingo_score: NullableInput;
  has_pte: boolean;
  pte_score: NullableInput;
  has_hsk: boolean;
  hsk_level: string;
  has_gre: boolean;
  gre_score: NullableInput;
  has_gmat: boolean;
  gmat_score: NullableInput;
  english_proficiency_certificate: boolean;
  has_cnic: boolean;
  has_domicile: boolean;
  has_passport: boolean;
  passport_expiry_date: string | null;
  has_transcript: boolean;
  has_degree: boolean;
  has_cv: boolean;
  has_sop: boolean;
  has_study_plan: boolean;
  has_recommendation_letters: boolean;
  recommendation_letters_count: NullableInput;
  has_research_proposal: boolean;
  has_publications: boolean;
  has_english_proficiency_letter: boolean;
  has_income_certificate: boolean;
  has_bank_statement: boolean;
  has_police_clearance: boolean;
  has_medical_certificate: boolean;
  additional_documents: string[];
  research_interests: string[];
  has_research_experience: boolean;
  publications_count: NullableInput;
  has_supervisor_acceptance: boolean;
  supervisor_country: string;
  supervisor_university: string;
  skills: string[];
  work_experience_years: NullableInput;
  has_internship_experience: boolean;
  linkedin_url: string;
  portfolio_url: string;
  github_url: string;
  need_based_support_required: boolean;
  can_pay_application_fee: boolean;
  max_application_fee_usd: NullableInput;
  can_self_fund_partial: boolean;
  special_scholarship_categories: string[];
  email_alerts_enabled: boolean;
  whatsapp_alerts_enabled: boolean;
  profile_data_consent: boolean;
  profile_source: "manual" | "cv_imported" | "admin_created" | "mixed" | "";
  ai_autofill_reviewed: boolean;
};

export type StudentProfile = StudentProfilePayload &
  ProfileCompletion & {
    id: number;
    user: number;
    created_at: string;
    updated_at: string;
  };
