# Generated by Django 6.0.5 on 2026-05-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aijob',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='aijob',
            name='estimated_wait_seconds',
            field=models.PositiveIntegerField(default=45),
        ),
        migrations.AlterField(
            model_name='aijob',
            name='queue_position_at_submit',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='aijob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='aijob',
            name='tool_type',
            field=models.CharField(choices=[('sop_generate', 'SOP Generate'), ('cv_generate', 'CV Generate'), ('motivation_letter', 'Motivation Letter')], max_length=50),
        ),
    ]
