# Generated by Django 6.0.5 on 2026-05-15 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_tools", "0002_alter_aijob_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SOPDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("local", "Server 1"),
                            ("puter", "Server 2"),
                            ("deepseek", "Server 3"),
                        ],
                        max_length=30,
                    ),
                ),
                ("provider_label", models.CharField(blank=True, max_length=80)),
                ("target_scholarship", models.CharField(blank=True, max_length=300)),
                ("target_country", models.CharField(blank=True, max_length=120)),
                ("target_degree", models.CharField(blank=True, max_length=120)),
                ("field_of_study", models.CharField(blank=True, max_length=200)),
                ("academic_background", models.TextField(blank=True)),
                ("key_strength", models.TextField(blank=True)),
                ("why_this_scholarship", models.TextField(blank=True)),
                ("future_goal", models.TextField(blank=True)),
                ("contribution_goal", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("sop_text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sop_drafts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"], name="ai_tools_so_user_id_e1aec7_idx"
                    )
                ],
            },
        ),
    ]
