# Generated by Django 6.0.5 on 2026-05-17 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_tools', '0003_sopdraft'),
        ('opportunities', '0006_opportunity_stipend_summary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sopdraft',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sop_drafts', to='opportunities.opportunity'),
        ),
        migrations.AddIndex(
            model_name='sopdraft',
            index=models.Index(fields=['user', 'opportunity', '-created_at'], name='ai_tools_so_user_id_2ca297_idx'),
        ),
    ]
