# Generated by Django 6.0.5 on 2026-05-08 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
        ("opportunities", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OpportunityApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("preparing", "Preparing"),
                            ("documents_pending", "Documents Pending"),
                            ("documents_ready", "Documents Ready"),
                            ("applied", "Applied"),
                            ("interview", "Interview"),
                            ("result_waiting", "Result Waiting"),
                            ("selected", "Selected"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                            ("deferred", "Deferred"),
                        ],
                        default="preparing",
                        max_length=40,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("next_step", models.CharField(blank=True, max_length=255)),
                ("reminder_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("decision_at", models.DateTimeField(blank=True, null=True)),
                ("personal_deadline", models.DateField(blank=True, null=True)),
                ("checklist_snapshot", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="application_trackers",
                        to="opportunities.opportunity",
                    ),
                ),
                (
                    "saved_opportunity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="application_trackers",
                        to="applications.savedopportunity",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunity_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at",),
                "indexes": [
                    models.Index(fields=["user"], name="application_user_id_de6110_idx"),
                    models.Index(fields=["opportunity"], name="application_opportu_9fd416_idx"),
                    models.Index(fields=["status"], name="application_status_f3aa9f_idx"),
                    models.Index(fields=["priority"], name="application_priorit_a3bde4_idx"),
                    models.Index(
                        fields=["personal_deadline"], name="application_persona_bac281_idx"
                    ),
                    models.Index(fields=["reminder_at"], name="application_reminde_7fc912_idx"),
                    models.Index(fields=["created_at"], name="application_created_d625db_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "opportunity"),
                        name="unique_application_per_user_opportunity",
                    )
                ],
            },
        ),
    ]
