from django.urls import path

from apps.applications.views import (
    OpportunitySaveView,
    OpportunityStartApplicationView,
    ScholarshipSaveView,
    ScholarshipStartApplicationView,
)
from apps.opportunities.views import (
    AdminOverviewView,
    AdminOpportunityCommentListView,
    AdminOpportunityCommentModerateView,
    AdminOpportunityDetailView,
    AdminOpportunityDuplicateCheckView,
    AdminOpportunityDraftDetailView,
    AdminOpportunityDraftImportView,
    AdminOpportunityDraftListCreateView,
    AdminOpportunityDraftValidateView,
    AdminOpportunityListCreateView,
    AdminOpportunityPathwayDetailView,
    AdminOpportunityPathwayListCreateView,
    AgentScholarshipCreateDraftView,
    AgentScholarshipValidateView,
    OpportunityCommentDeleteView,
    OpportunityMatchView,
    PublicOpportunityDetailView,
    PublicOpportunityListView,
    PublicOpportunityPathwayDetailView,
    PublicOpportunityPathwayListView,
    PublicScholarshipDetailView,
    PublicScholarshipListView,
    ScholarshipPickerView,
    RecommendedOpportunitiesView,
    RecommendedScholarshipsView,
    ScholarshipCommentListCreateView,
    ScholarshipCommentReplyCreateView,
    ScholarshipMatchView,
)

urlpatterns = [
    path(
        "opportunity-pathways/",
        PublicOpportunityPathwayListView.as_view(),
        name="opportunity-pathway-list",
    ),
    path(
        "opportunity-pathways/<slug:slug>/",
        PublicOpportunityPathwayDetailView.as_view(),
        name="opportunity-pathway-detail",
    ),
    path("opportunities/", PublicOpportunityListView.as_view(), name="opportunity-list"),
    path(
        "opportunities/recommended/",
        RecommendedOpportunitiesView.as_view(),
        name="opportunity-recommended",
    ),
    path(
        "opportunities/<slug:slug>/match/",
        OpportunityMatchView.as_view(),
        name="opportunity-match",
    ),
    path(
        "opportunities/<slug:slug>/save/",
        OpportunitySaveView.as_view(),
        name="opportunity-save",
    ),
    path(
        "opportunities/<slug:slug>/start-application/",
        OpportunityStartApplicationView.as_view(),
        name="opportunity-start-application",
    ),
    path(
        "opportunities/<slug:slug>/",
        PublicOpportunityDetailView.as_view(),
        name="opportunity-detail",
    ),
    path("scholarships/", PublicScholarshipListView.as_view(), name="scholarship-list"),
    path(
        "scholarships/picker/",
        ScholarshipPickerView.as_view(),
        name="scholarship-picker",
    ),
    path(
        "scholarships/recommended/",
        RecommendedScholarshipsView.as_view(),
        name="scholarship-recommended",
    ),
    path(
        "scholarships/<slug:slug>/match/",
        ScholarshipMatchView.as_view(),
        name="scholarship-match",
    ),
    path(
        "scholarships/<slug:slug>/comments/",
        ScholarshipCommentListCreateView.as_view(),
        name="scholarship-comments",
    ),
    path(
        "scholarships/<slug:slug>/comments/<int:pk>/replies/",
        ScholarshipCommentReplyCreateView.as_view(),
        name="scholarship-comment-replies",
    ),
    path(
        "scholarship-comments/<int:pk>/",
        OpportunityCommentDeleteView.as_view(),
        name="scholarship-comment-delete",
    ),
    path(
        "scholarships/<slug:slug>/save/",
        ScholarshipSaveView.as_view(),
        name="scholarship-save",
    ),
    path(
        "scholarships/<slug:slug>/start-application/",
        ScholarshipStartApplicationView.as_view(),
        name="scholarship-start-application",
    ),
    path(
        "scholarships/<slug:slug>/",
        PublicScholarshipDetailView.as_view(),
        name="scholarship-detail",
    ),
    path(
        "admin/overview/",
        AdminOverviewView.as_view(),
        name="admin-overview",
    ),
    path(
        "admin/agent/scholarships/validate/",
        AgentScholarshipValidateView.as_view(),
        name="agent-scholarship-validate",
    ),
    path(
        "admin/agent/scholarships/create-draft/",
        AgentScholarshipCreateDraftView.as_view(),
        name="agent-scholarship-create-draft",
    ),
    path(
        "admin/opportunity-pathways/",
        AdminOpportunityPathwayListCreateView.as_view(),
        name="admin-opportunity-pathway-list",
    ),
    path(
        "admin/opportunity-pathways/<int:pk>/",
        AdminOpportunityPathwayDetailView.as_view(),
        name="admin-opportunity-pathway-detail",
    ),
    path(
        "admin/comments/",
        AdminOpportunityCommentListView.as_view(),
        name="admin-comment-list",
    ),
    path(
        "admin/comments/<int:pk>/",
        AdminOpportunityCommentModerateView.as_view(),
        name="admin-comment-moderate",
    ),
    path(
        "admin/opportunity-drafts/",
        AdminOpportunityDraftListCreateView.as_view(),
        name="admin-opportunity-draft-list",
    ),
    path(
        "admin/opportunity-drafts/<int:pk>/",
        AdminOpportunityDraftDetailView.as_view(),
        name="admin-opportunity-draft-detail",
    ),
    path(
        "admin/opportunity-drafts/<int:pk>/validate/",
        AdminOpportunityDraftValidateView.as_view(),
        name="admin-opportunity-draft-validate",
    ),
    path(
        "admin/opportunity-drafts/<int:pk>/import/",
        AdminOpportunityDraftImportView.as_view(),
        name="admin-opportunity-draft-import",
    ),
    path(
        "admin/opportunities/",
        AdminOpportunityListCreateView.as_view(),
        name="admin-opportunity-list",
    ),
    path(
        "admin/opportunities/check-duplicates/",
        AdminOpportunityDuplicateCheckView.as_view(),
        name="admin-opportunity-duplicate-check",
    ),
    path(
        "admin/opportunities/<int:pk>/",
        AdminOpportunityDetailView.as_view(),
        name="admin-opportunity-detail",
    ),
]
