# Generated by Django 6.0.5 on 2026-05-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=280, unique=True)),
                (
                    "opportunity_type",
                    models.CharField(
                        choices=[
                            ("scholarship", "Scholarship"),
                            ("job", "Job"),
                            ("internship", "Internship"),
                            ("fellowship", "Fellowship"),
                            ("exchange_program", "Exchange program"),
                            ("research_position", "Research position"),
                            ("admission", "Admission"),
                            ("competition", "Competition"),
                            ("training", "Training"),
                            ("mentorship_program", "Mentorship program"),
                        ],
                        db_index=True,
                        default="scholarship",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=30,
                    ),
                ),
                ("featured", models.BooleanField(db_index=True, default=False)),
                ("verified_status", models.BooleanField(db_index=True, default=False)),
                ("verification_note", models.CharField(blank=True, max_length=255)),
                ("last_verified_at", models.DateTimeField(blank=True, null=True)),
                ("provider_name", models.CharField(blank=True, max_length=255)),
                (
                    "organization_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("university", "University"),
                            ("government", "Government"),
                            ("company", "Company"),
                            ("ngo", "NGO"),
                            ("foundation", "Foundation"),
                            ("international_organization", "International organization"),
                            ("private_provider", "Private provider"),
                            ("other", "Other"),
                        ],
                        max_length=80,
                    ),
                ),
                ("university_name", models.CharField(blank=True, max_length=255)),
                ("company_name", models.CharField(blank=True, max_length=255)),
                ("country", models.CharField(blank=True, db_index=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=120)),
                (
                    "location_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("on_site", "On-site"),
                            ("remote", "Remote"),
                            ("hybrid", "Hybrid"),
                            ("not_applicable", "Not applicable"),
                        ],
                        max_length=50,
                    ),
                ),
                ("short_description", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("benefits", models.TextField(blank=True)),
                ("eligibility", models.TextField(blank=True)),
                ("how_to_apply", models.TextField(blank=True)),
                ("official_link", models.URLField(blank=True)),
                ("source_url", models.URLField(blank=True)),
                ("source_name", models.CharField(blank=True, max_length=255)),
                ("eligible_countries", models.JSONField(blank=True, default=list)),
                ("degree_levels", models.JSONField(blank=True, default=list)),
                ("fields_of_study", models.JSONField(blank=True, default=list)),
                ("target_regions", models.JSONField(blank=True, default=list)),
                (
                    "gender_eligibility",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("all", "All"),
                            ("women_only", "Women only"),
                            ("men_only", "Men only"),
                            ("not_specified", "Not specified"),
                        ],
                        default="not_specified",
                        max_length=50,
                    ),
                ),
                (
                    "min_cgpa",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
                ),
                (
                    "min_percentage",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                ("min_education_level", models.CharField(blank=True, max_length=80)),
                (
                    "funding_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("fully_funded", "Fully funded"),
                            ("partially_funded", "Partially funded"),
                            ("tuition_waiver", "Tuition waiver"),
                            ("stipend_only", "Stipend only"),
                            ("need_based", "Need based"),
                            ("merit_based", "Merit based"),
                            ("self_funded", "Self funded"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=80,
                    ),
                ),
                (
                    "funding_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("funding_currency", models.CharField(blank=True, max_length=10)),
                ("application_fee_required", models.BooleanField(default=False)),
                (
                    "application_fee_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                ("application_fee_currency", models.CharField(blank=True, max_length=10)),
                ("hec_required", models.BooleanField(default=False)),
                ("ielts_required", models.BooleanField(default=False)),
                ("toefl_required", models.BooleanField(default=False)),
                ("duolingo_required", models.BooleanField(default=False)),
                ("hsk_required", models.BooleanField(default=False)),
                ("english_proficiency_certificate_accepted", models.BooleanField(default=False)),
                (
                    "employment_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("full_time", "Full time"),
                            ("part_time", "Part time"),
                            ("contract", "Contract"),
                            ("internship", "Internship"),
                            ("volunteer", "Volunteer"),
                            ("freelance", "Freelance"),
                            ("temporary", "Temporary"),
                            ("not_applicable", "Not applicable"),
                        ],
                        max_length=80,
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("entry_level", "Entry level"),
                            ("student", "Student"),
                            ("fresh_graduate", "Fresh graduate"),
                            ("mid_level", "Mid level"),
                            ("senior", "Senior"),
                            ("not_applicable", "Not applicable"),
                        ],
                        max_length=80,
                    ),
                ),
                (
                    "min_experience_years",
                    models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
                ),
                ("required_skills", models.JSONField(blank=True, default=list)),
                (
                    "salary_min",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "salary_max",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("salary_currency", models.CharField(blank=True, max_length=10)),
                ("deadline", models.DateField(blank=True, db_index=True, null=True)),
                ("is_rolling_deadline", models.BooleanField(default=False)),
                ("application_open_date", models.DateField(blank=True, null=True)),
                (
                    "application_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("official_website", "Official website"),
                            ("email", "Email"),
                            ("hec_portal", "HEC portal"),
                            ("university_portal", "University portal"),
                            ("company_portal", "Company portal"),
                            ("external_form", "External form"),
                            ("other", "Other"),
                        ],
                        max_length=80,
                    ),
                ),
                ("required_documents", models.JSONField(blank=True, default=list)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("search_keywords", models.TextField(blank=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-featured", "deadline", "-published_at"),
                "indexes": [
                    models.Index(
                        fields=["opportunity_type"], name="opportuniti_opportu_a0cf41_idx"
                    ),
                    models.Index(fields=["status"], name="opportuniti_status_fb4df4_idx"),
                    models.Index(fields=["country"], name="opportuniti_country_20b9f3_idx"),
                    models.Index(fields=["deadline"], name="opportuniti_deadlin_294f61_idx"),
                    models.Index(fields=["featured"], name="opportuniti_feature_cec9b7_idx"),
                    models.Index(fields=["verified_status"], name="opportuniti_verifie_2589cb_idx"),
                    models.Index(fields=["funding_type"], name="opportuniti_funding_ce2398_idx"),
                    models.Index(fields=["created_at"], name="opportuniti_created_5f72d6_idx"),
                ],
            },
        ),
    ]
