# Generated by Django 6.0.5 on 2026-05-11 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0002_opportunitycomment'),
        ('reference_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='opportunity',
            name='opportuniti_country_20b9f3_idx',
        ),
        migrations.AddField(
            model_name='opportunity',
            name='all_study_fields',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='country_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='reference_data.country'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='eligible_country_refs',
            field=models.ManyToManyField(blank=True, related_name='eligible_opportunities', to='reference_data.country'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='eligible_region_refs',
            field=models.ManyToManyField(blank=True, related_name='eligible_opportunities', to='reference_data.region'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='study_field_refs',
            field=models.ManyToManyField(blank=True, related_name='opportunities', to='reference_data.studyfield'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['country_ref'], name='opportuniti_country_995443_idx'),
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='country',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='eligible_countries',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='fields_of_study',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='target_regions',
        ),
    ]
