# Generated by Django 6.0.5 on 2026-05-11 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opportunities", "0003_remove_opportunity_opportuniti_country_20b9f3_idx_and_more"),
        ("reference_data", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunity",
            name="application_track",
            field=models.CharField(
                blank=True,
                choices=[
                    ("embassy", "Embassy"),
                    ("university", "University"),
                    ("direct", "Direct"),
                    ("professor", "Professor"),
                    ("regional", "Regional"),
                    ("portal", "Portal"),
                    ("other", "Other"),
                ],
                db_index=True,
                max_length=80,
            ),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="department_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="lab_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="professor_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="professor_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name="OpportunityPathway",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=280, unique=True)),
                (
                    "pathway_type",
                    models.CharField(
                        choices=[
                            ("country_hub", "Country hub"),
                            ("government_program", "Government program"),
                            ("scholarship_program", "Scholarship program"),
                            ("application_track", "Application track"),
                            ("university_group", "University group"),
                            ("professor_lab_group", "Professor/lab group"),
                            ("regional_scholarship", "Regional scholarship"),
                            ("university_scholarship", "University scholarship"),
                            ("guide", "Guide"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=80,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("official_link", models.URLField(blank=True)),
                ("display_order", models.PositiveIntegerField(db_index=True, default=100)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "country_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="opportunity_pathways",
                        to="reference_data.country",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="opportunities.opportunitypathway",
                    ),
                ),
            ],
            options={
                "ordering": ("display_order", "title"),
            },
        ),
        migrations.AddField(
            model_name="opportunity",
            name="pathway",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="opportunities",
                to="opportunities.opportunitypathway",
            ),
        ),
        migrations.AddIndex(
            model_name="opportunitypathway",
            index=models.Index(fields=["slug"], name="opportuniti_slug_e5137b_idx"),
        ),
        migrations.AddIndex(
            model_name="opportunitypathway",
            index=models.Index(fields=["country_ref"], name="opportuniti_country_6fcf63_idx"),
        ),
        migrations.AddIndex(
            model_name="opportunitypathway",
            index=models.Index(fields=["pathway_type"], name="opportuniti_pathway_92a9ea_idx"),
        ),
        migrations.AddIndex(
            model_name="opportunitypathway",
            index=models.Index(fields=["is_active"], name="opportuniti_is_acti_b4f134_idx"),
        ),
    ]
