# Generated by Django 6.0.5 on 2026-05-12 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opportunities", "0004_opportunity_application_track_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OpportunityDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=280, unique=True)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("validated", "Validated"),
                            ("imported", "Imported"),
                            ("error", "Error"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=30,
                    ),
                ),
                ("source_url", models.URLField(blank=True)),
                ("source_name", models.CharField(blank=True, max_length=255)),
                ("confidence", models.CharField(blank=True, max_length=32)),
                ("validation_warnings", models.JSONField(blank=True, default=list)),
                ("validation_errors", models.JSONField(blank=True, default=list)),
                ("imported_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opportunity_drafts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_opportunity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_drafts",
                        to="opportunities.opportunity",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at", "title"),
                "indexes": [
                    models.Index(fields=["status"], name="opportuniti_status_b7d96b_idx"),
                    models.Index(fields=["slug"], name="opportuniti_slug_de5ad9_idx"),
                    models.Index(fields=["created_at"], name="opportuniti_created_5b7efd_idx"),
                ],
            },
        ),
    ]
