# Generated by Django 6.0.5 on 2026-05-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0005_opportunitydraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='stipend_summary',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
