# Generated by Django 6.0.5 on 2026-05-19 13:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0006_opportunity_stipend_summary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunitycomment',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'Pending review'), ('active', 'Active'), ('deleted', 'Deleted')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='opportunitycomment',
            index=models.Index(fields=['moderation_status'], name='opportuniti_moderat_1a4f9b_idx'),
        ),
    ]
