# Generated by Django 6.0.5 on 2026-05-21 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opportunities", "0007_opportunitycomment_moderation_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpportunitySocialDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("facebook_post_text", models.TextField(blank=True)),
                ("facebook_image_prompt", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("approved", "Approved"),
                            ("posted", "Posted"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "opportunity_draft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_drafts",
                        to="opportunities.opportunitydraft",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at",),
                "indexes": [
                    models.Index(fields=["status"], name="opportuniti_status_a455fe_idx"),
                    models.Index(fields=["created_at"], name="opportuniti_created_677dd2_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("opportunity_draft",),
                        name="unique_social_draft_per_opportunity_draft",
                    )
                ],
            },
        ),
    ]
