# Generated by Django 6.0.5 on 2026-05-25 04:58

import django.db.models.deletion
from django.db import migrations, models


def forwards_social_draft_status(apps, schema_editor):
    social_draft = apps.get_model("opportunities", "OpportunitySocialDraft")
    social_draft.objects.filter(status="approved").update(status="ready")


def backwards_social_draft_status(apps, schema_editor):
    social_draft = apps.get_model("opportunities", "OpportunitySocialDraft")
    social_draft.objects.filter(status="ready").update(status="approved")


class Migration(migrations.Migration):

    dependencies = [
        ("opportunities", "0008_opportunitysocialdraft"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunitysocialdraft",
            name="facebook_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="opportunity_social_drafts/facebook/%Y/%m/"
            ),
        ),
        migrations.AddField(
            model_name="opportunitysocialdraft",
            name="facebook_image_url",
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(forwards_social_draft_status, backwards_social_draft_status),
        migrations.AlterField(
            model_name="opportunitysocialdraft",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("ready", "Ready"), ("posted", "Posted")],
                db_index=True,
                default="draft",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="OpportunitySocialPostPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("platform", models.CharField(db_index=True, default="facebook", max_length=50)),
                ("enabled", models.BooleanField(db_index=True, default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("ready", "Ready"),
                            ("paused", "Paused"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=30,
                    ),
                ),
                ("post_text", models.TextField(blank=True)),
                ("image_prompt", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="opportunity_social/facebook/%Y/%m/"
                    ),
                ),
                ("image_url", models.TextField(blank=True)),
                ("link_url", models.TextField(blank=True)),
                ("last_posted_at", models.DateTimeField(blank=True, null=True)),
                ("next_post_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("post_count", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_post_plans",
                        to="opportunities.opportunity",
                    ),
                ),
            ],
            options={
                "ordering": ("next_post_at", "-updated_at"),
            },
        ),
        migrations.CreateModel(
            name="OpportunitySocialPostLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("platform", models.CharField(db_index=True, default="facebook", max_length=50)),
                ("message", models.TextField(blank=True)),
                ("image_url", models.TextField(blank=True)),
                ("link_url", models.TextField(blank=True)),
                ("facebook_post_id", models.CharField(blank=True, max_length=255)),
                ("facebook_post_url", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("posted", "Posted"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_post_logs",
                        to="opportunities.opportunity",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="opportunities.opportunitysocialpostplan",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="opportunitysocialpostplan",
            index=models.Index(
                fields=["platform", "enabled", "status"], name="opportuniti_platfor_2b04de_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="opportunitysocialpostplan",
            index=models.Index(fields=["last_posted_at"], name="opportuniti_last_po_fc6ef8_idx"),
        ),
        migrations.AddIndex(
            model_name="opportunitysocialpostplan",
            index=models.Index(fields=["created_at"], name="opportuniti_created_c785a4_idx"),
        ),
        migrations.AddConstraint(
            model_name="opportunitysocialpostplan",
            constraint=models.UniqueConstraint(
                fields=("opportunity", "platform"),
                name="unique_social_post_plan_per_opportunity_platform",
            ),
        ),
        migrations.AddIndex(
            model_name="opportunitysocialpostlog",
            index=models.Index(
                fields=["platform", "status"], name="opportuniti_platfor_fb839e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="opportunitysocialpostlog",
            index=models.Index(fields=["posted_at"], name="opportuniti_posted__68b49d_idx"),
        ),
        migrations.AddIndex(
            model_name="opportunitysocialpostlog",
            index=models.Index(fields=["created_at"], name="opportuniti_created_e42daa_idx"),
        ),
    ]
