# Generated by Django 6.0.5 on 2026-05-25 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opportunities", "0009_opportunitysocialdraft_facebook_image_and_more"),
        ("reference_data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpportunityDeadlineCheckLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("old_deadline", models.DateField(blank=True, null=True)),
                ("new_deadline", models.DateField(blank=True, null=True)),
                ("old_status", models.CharField(blank=True, max_length=30)),
                ("new_status", models.CharField(blank=True, max_length=30)),
                (
                    "check_status",
                    models.CharField(
                        choices=[
                            ("unchecked", "Unchecked"),
                            ("verified_active", "Verified active"),
                            ("verified_expired", "Verified expired"),
                            ("deadline_changed", "Deadline changed"),
                            ("unclear", "Unclear"),
                            ("source_unreachable", "Source unreachable"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("source_url", models.URLField(blank=True)),
                ("evidence", models.TextField(blank=True)),
                ("note", models.TextField(blank=True)),
                ("checked_by", models.CharField(default="agent", max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddField(
            model_name="opportunity",
            name="deadline_check_evidence",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="deadline_check_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="deadline_check_source_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="deadline_check_status",
            field=models.CharField(
                choices=[
                    ("unchecked", "Unchecked"),
                    ("verified_active", "Verified active"),
                    ("verified_expired", "Verified expired"),
                    ("deadline_changed", "Deadline changed"),
                    ("unclear", "Unclear"),
                    ("source_unreachable", "Source unreachable"),
                ],
                db_index=True,
                default="unchecked",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="deadline_last_checked_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name="opportunity",
            index=models.Index(
                fields=["deadline_last_checked_at"], name="opportuniti_deadlin_985ebf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="opportunity",
            index=models.Index(
                fields=["deadline_check_status"], name="opportuniti_deadlin_64874a_idx"
            ),
        ),
        migrations.AddField(
            model_name="opportunitydeadlinechecklog",
            name="opportunity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deadline_check_logs",
                to="opportunities.opportunity",
            ),
        ),
        migrations.AddIndex(
            model_name="opportunitydeadlinechecklog",
            index=models.Index(fields=["check_status"], name="opportuniti_check_s_a6ed1a_idx"),
        ),
        migrations.AddIndex(
            model_name="opportunitydeadlinechecklog",
            index=models.Index(fields=["created_at"], name="opportuniti_created_b4ff1e_idx"),
        ),
    ]
