# Generated by Django 6.0.5 on 2026-05-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opportunities", "0010_opportunitydeadlinechecklog_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunitysocialdraft",
            name="social_image_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="opportunitysocialdraft",
            name="social_image_saved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="opportunitysocialdraft",
            name="social_image_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("gpt_uploaded", "GPT uploaded"),
                    ("gpt_image_url", "GPT image URL"),
                    ("gpt_base64", "GPT base64"),
                    ("backend_generated", "Backend generated"),
                    ("og_fallback", "Open Graph fallback"),
                ],
                db_index=True,
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="opportunitysocialdraft",
            name="social_image_status",
            field=models.CharField(
                choices=[
                    ("missing", "Missing"),
                    ("saved", "Saved"),
                    ("failed", "Failed"),
                    ("fallback", "Fallback"),
                ],
                db_index=True,
                default="missing",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="opportunitysocialpostlog",
            name="image_source",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="opportunitysocialpostplan",
            name="social_image_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="opportunitysocialpostplan",
            name="social_image_saved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="opportunitysocialpostplan",
            name="social_image_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("gpt_uploaded", "GPT uploaded"),
                    ("gpt_image_url", "GPT image URL"),
                    ("gpt_base64", "GPT base64"),
                    ("backend_generated", "Backend generated"),
                    ("og_fallback", "Open Graph fallback"),
                ],
                db_index=True,
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="opportunitysocialpostplan",
            name="social_image_status",
            field=models.CharField(
                choices=[
                    ("missing", "Missing"),
                    ("saved", "Saved"),
                    ("failed", "Failed"),
                    ("fallback", "Fallback"),
                ],
                db_index=True,
                default="missing",
                max_length=30,
            ),
        ),
    ]
