# Generated by Django 6.0.5 on 2026-05-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opportunities", "0011_opportunitysocialdraft_social_image_error_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunity",
            name="deadline_check_confidence",
            field=models.CharField(
                blank=True,
                choices=[("high", "High"), ("medium", "Medium"), ("low", "Low")],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="deadline_previous_value",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="deadline_updated_from_source_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="opportunitydeadlinechecklog",
            name="checked_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="opportunitydeadlinechecklog",
            name="confidence",
            field=models.CharField(
                blank=True,
                choices=[("high", "High"), ("medium", "Medium"), ("low", "Low")],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="opportunitydeadlinechecklog",
            name="detected_deadline",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="opportunitydeadlinechecklog",
            name="error_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="opportunitydeadlinechecklog",
            name="evidence_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="opportunitydeadlinechecklog",
            name="raw_response_excerpt",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="opportunitydeadlinechecklog",
            name="status",
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AddField(
            model_name="opportunitydeadlinechecklog",
            name="verifier",
            field=models.CharField(db_index=True, default="agent", max_length=40),
        ),
        migrations.AddField(
            model_name="opportunitysocialdraft",
            name="social_image_is_stale",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="deadline_check_status",
            field=models.CharField(
                choices=[
                    ("unchecked", "Unchecked"),
                    ("verified_active", "Verified active"),
                    ("verified_expired", "Verified expired"),
                    ("deadline_changed", "Deadline changed"),
                    ("unclear", "Unclear"),
                    ("source_unreachable", "Source unreachable"),
                    ("confirmed", "Confirmed"),
                    ("extended", "Extended"),
                    ("expired", "Expired"),
                    ("failed", "Failed"),
                    ("needs_review", "Needs review"),
                ],
                db_index=True,
                default="unchecked",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="opportunitydeadlinechecklog",
            name="check_status",
            field=models.CharField(
                choices=[
                    ("unchecked", "Unchecked"),
                    ("verified_active", "Verified active"),
                    ("verified_expired", "Verified expired"),
                    ("deadline_changed", "Deadline changed"),
                    ("unclear", "Unclear"),
                    ("source_unreachable", "Source unreachable"),
                    ("confirmed", "Confirmed"),
                    ("extended", "Extended"),
                    ("expired", "Expired"),
                    ("failed", "Failed"),
                    ("needs_review", "Needs review"),
                ],
                db_index=True,
                max_length=40,
            ),
        ),
    ]
