# Generated by Django 6.0.5 on 2026-05-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opportunities", "0012_opportunity_deadline_check_confidence_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunitysocialpostplan",
            name="social_image_is_stale",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
