# Generated by Django 6.0.5 on 2026-05-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opportunities", "0013_opportunitysocialpostplan_social_image_is_stale"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opportunitydeadlinechecklog",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("confirmed", "Confirmed"),
                    ("extended", "Extended"),
                    ("expired", "Expired"),
                    ("unclear", "Unclear"),
                    ("failed", "Failed"),
                    ("needs_review", "Needs review"),
                ],
                db_index=True,
                max_length=40,
            ),
        ),
    ]
