# Generated by Django 6.0.5 on 2026-05-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opportunities", "0015_opportunitysourcelinkcorrectionlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScholarshipResearchLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("provider_name", models.CharField(blank=True, max_length=255)),
                ("country", models.CharField(blank=True, max_length=120)),
                ("city", models.CharField(blank=True, max_length=120)),
                ("university", models.CharField(blank=True, max_length=255)),
                ("degree_level", models.CharField(blank=True, max_length=120)),
                ("funding_type", models.CharField(blank=True, max_length=120)),
                ("official_url", models.URLField(blank=True, max_length=2000)),
                ("source_url", models.URLField(blank=True, max_length=2000)),
                ("detected_deadline", models.DateField(blank=True, null=True)),
                ("deadline_text", models.CharField(blank=True, max_length=255)),
                ("eligibility_summary", models.TextField(blank=True)),
                ("pakistan_relevance_score", models.PositiveSmallIntegerField(default=0)),
                (
                    "duplicate_status",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("new", "New"),
                            ("possible_duplicate", "Possible duplicate"),
                            ("duplicate", "Duplicate"),
                        ],
                        db_index=True,
                        default="unknown",
                        max_length=40,
                    ),
                ),
                ("duplicate_matches", models.JSONField(blank=True, default=list)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("needs_review", "Needs review"),
                            ("ready_for_draft", "Ready for draft"),
                            ("rejected", "Rejected"),
                            ("imported", "Imported"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=40,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_by_agent", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["review_status", "duplicate_status"],
                        name="opportuniti_review__8ace10_idx",
                    ),
                    models.Index(fields=["country"], name="opportuniti_country_009fe2_idx"),
                    models.Index(fields=["degree_level"], name="opportuniti_degree__8ca49f_idx"),
                    models.Index(fields=["provider_name"], name="opportuniti_provide_ed788e_idx"),
                    models.Index(fields=["created_at"], name="opportuniti_created_801455_idx"),
                ],
            },
        ),
    ]
