# Generated by Django 6.0.5 on 2026-05-30 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opportunities", "0016_scholarshipresearchlead"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opportunity",
            name="deadline_check_source_url",
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="official_link",
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="source_url",
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="opportunitydeadlinechecklog",
            name="source_url",
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="opportunitydraft",
            name="source_url",
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="opportunitypathway",
            name="official_link",
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
