# Generated by Django 6.0.5 on 2026-05-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opportunities", "0017_alter_opportunity_deadline_check_source_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunitysocialpostplan",
            name="auto_social_decision",
            field=models.CharField(
                choices=[
                    ("individual", "Individual"),
                    ("collection_candidate", "Collection candidate"),
                    ("website_only", "Website only"),
                    ("manual_review", "Manual review"),
                ],
                db_index=True,
                default="website_only",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="opportunitysocialpostplan",
            name="priority_reason",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="opportunitysocialpostplan",
            name="priority_score",
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name="opportunitysocialpostplan",
            index=models.Index(
                fields=["auto_social_decision", "priority_score"],
                name="opportuniti_auto_so_8e59c1_idx",
            ),
        ),
    ]
