# Generated by Django 6.0.5 on 2026-05-30 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opportunities", "0018_opportunitysocialpostplan_auto_social_decision_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpportunityCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=280, unique=True)),
                ("description", models.TextField(blank=True)),
                ("intro_text", models.TextField(blank=True)),
                (
                    "collection_type",
                    models.CharField(
                        choices=[
                            ("country_degree", "Country and degree"),
                            ("country_funding", "Country and funding"),
                            ("degree_funding", "Degree and funding"),
                            ("field", "Field"),
                            ("deadline_window", "Deadline window"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("country", models.CharField(blank=True, db_index=True, max_length=120)),
                ("degree_level", models.CharField(blank=True, db_index=True, max_length=120)),
                ("funding_type", models.CharField(blank=True, db_index=True, max_length=120)),
                ("field_label", models.CharField(blank=True, db_index=True, max_length=160)),
                ("deadline_start", models.DateField(blank=True, db_index=True, null=True)),
                ("deadline_end", models.DateField(blank=True, db_index=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("ready", "Ready"),
                            ("approved", "Approved"),
                            ("posted", "Posted"),
                            ("paused", "Paused"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=30,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("system", "System"), ("admin", "Admin")],
                        db_index=True,
                        default="system",
                        max_length=30,
                    ),
                ),
                ("social_post_text", models.TextField(blank=True)),
                ("priority_score", models.IntegerField(db_index=True, default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-priority_score", "-created_at"),
                "indexes": [
                    models.Index(fields=["status", "source"], name="opportuniti_status_f78a63_idx"),
                    models.Index(
                        fields=["collection_type", "status"], name="opportuniti_collect_a39039_idx"
                    ),
                    models.Index(fields=["priority_score"], name="opportuniti_priorit_0f931b_idx"),
                    models.Index(fields=["created_at"], name="opportuniti_created_2aea19_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="OpportunityCollectionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("position", models.PositiveIntegerField(db_index=True, default=0)),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="opportunities.opportunitycollection",
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_items",
                        to="opportunities.opportunity",
                    ),
                ),
                (
                    "social_post_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="collection_items",
                        to="opportunities.opportunitysocialpostplan",
                    ),
                ),
            ],
            options={
                "ordering": ("position", "id"),
                "indexes": [
                    models.Index(fields=["position"], name="opportuniti_positio_65ffcd_idx"),
                    models.Index(fields=["created_at"], name="opportuniti_created_e13874_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("collection", "opportunity"),
                        name="unique_collection_opportunity_item",
                    )
                ],
            },
        ),
    ]
