# Generated by Django 6.0.5 on 2026-05-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opportunities", "0019_opportunitycollection_opportunitycollectionitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunitycollection",
            name="approval_source",
            field=models.CharField(
                blank=True,
                choices=[("system", "System"), ("admin", "Admin"), ("manual", "Manual")],
                db_index=True,
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="opportunitycollection",
            name="auto_approval_reason",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="opportunitycollection",
            name="auto_approval_score",
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="opportunitycollection",
            name="auto_approved_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
