# Generated by Django 6.0.5 on 2026-05-30 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0020_opportunitycollection_approval_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityCollectionSocialPostPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(db_index=True, default='facebook', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('paused', 'Paused'), ('posted', 'Posted'), ('failed', 'Failed'), ('archived', 'Archived')], db_index=True, default='ready', max_length=30)),
                ('post_text', models.TextField(blank=True)),
                ('link_url', models.TextField(blank=True)),
                ('image_url', models.TextField(blank=True)),
                ('image_source', models.CharField(blank=True, max_length=80)),
                ('next_post_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('priority_score', models.IntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_post_plans', to='opportunities.opportunitycollection')),
            ],
            options={
                'ordering': ('next_post_at', '-priority_score', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='OpportunityCollectionSocialPostLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(db_index=True, default='facebook', max_length=50)),
                ('status', models.CharField(choices=[('posted', 'Posted'), ('skipped', 'Skipped'), ('failed', 'Failed')], db_index=True, max_length=30)),
                ('facebook_post_id', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_post_logs', to='opportunities.opportunitycollection')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='opportunities.opportunitycollectionsocialpostplan')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='opportunitycollectionsocialpostplan',
            index=models.Index(fields=['platform', 'status'], name='opportuniti_platfor_83023f_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunitycollectionsocialpostplan',
            index=models.Index(fields=['priority_score'], name='opportuniti_priorit_a37542_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunitycollectionsocialpostplan',
            index=models.Index(fields=['next_post_at'], name='opportuniti_next_po_18d528_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunitycollectionsocialpostplan',
            index=models.Index(fields=['created_at'], name='opportuniti_created_95add4_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunitycollectionsocialpostlog',
            index=models.Index(fields=['platform', 'status'], name='opportuniti_platfor_1787fe_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunitycollectionsocialpostlog',
            index=models.Index(fields=['created_at'], name='opportuniti_created_9624bd_idx'),
        ),
    ]
