# Generated by Django 6.0.5 on 2026-05-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0021_opportunitycollectionsocialpostplan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunitycollectionsocialpostplan',
            name='facebook_post_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
