# Generated by Django 6.0.5 on 2026-06-02 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opportunities", "0022_opportunitycollectionsocialpostplan_facebook_post_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpportunityReelPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "reel_type",
                    models.CharField(
                        choices=[
                            ("closing_soon", "Closing soon"),
                            ("prepare_early", "Prepare early"),
                            ("single_scholarship", "Single scholarship"),
                            ("collection", "Collection"),
                        ],
                        db_index=True,
                        default="single_scholarship",
                        max_length=40,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("ready_for_render", "Ready for render"),
                            ("rendering", "Rendering"),
                            ("rendered", "Rendered"),
                            ("ready", "Ready"),
                            ("posted", "Posted"),
                            ("failed", "Failed"),
                            ("paused", "Paused"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=40,
                    ),
                ),
                ("scenes_json", models.JSONField(blank=True, default=list)),
                ("script_text", models.TextField(blank=True)),
                ("voiceover_text", models.TextField(blank=True)),
                ("caption_text", models.TextField(blank=True)),
                ("hashtags", models.TextField(blank=True)),
                ("source_opportunity_ids", models.JSONField(blank=True, default=list)),
                (
                    "video_file",
                    models.FileField(
                        blank=True, null=True, upload_to="opportunity_reels/videos/%Y/%m/"
                    ),
                ),
                ("video_url", models.TextField(blank=True)),
                (
                    "thumbnail_file",
                    models.ImageField(
                        blank=True, null=True, upload_to="opportunity_reels/thumbnails/%Y/%m/"
                    ),
                ),
                ("render_error", models.TextField(blank=True)),
                ("next_post_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("priority_score", models.IntegerField(db_index=True, default=0)),
                ("deadline_window", models.CharField(blank=True, db_index=True, max_length=60)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_collection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reel_plans",
                        to="opportunities.opportunitycollection",
                    ),
                ),
            ],
            options={
                "ordering": ("-priority_score", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="OpportunityReelLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("rendered", "Rendered"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("response_payload", models.JSONField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "reel_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="opportunities.opportunityreelplan",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="opportunityreelplan",
            index=models.Index(
                fields=["reel_type", "status"], name="opportuniti_reel_ty_ef4e49_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="opportunityreelplan",
            index=models.Index(
                fields=["status", "next_post_at"], name="opportuniti_status_d85649_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="opportunityreelplan",
            index=models.Index(fields=["deadline_window"], name="opportuniti_deadlin_ccc3d5_idx"),
        ),
        migrations.AddIndex(
            model_name="opportunityreelplan",
            index=models.Index(fields=["created_at"], name="opportuniti_created_28262e_idx"),
        ),
        migrations.AddIndex(
            model_name="opportunityreellog",
            index=models.Index(fields=["status"], name="opportuniti_status_c12cd6_idx"),
        ),
        migrations.AddIndex(
            model_name="opportunityreellog",
            index=models.Index(fields=["created_at"], name="opportuniti_created_d9cef3_idx"),
        ),
    ]
