# Generated by Django 6.0.5 on 2026-06-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opportunities", "0023_opportunityreelplan_opportunityreellog_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunityreelplan",
            name="template_key",
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
    ]
