# Generated by Django 6.0.5 on 2026-06-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opportunities", "0024_opportunityreelplan_template_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunityreelplan",
            name="facebook_post_id",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name="opportunityreelplan",
            name="facebook_video_id",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name="opportunityreelplan",
            name="facebook_posted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="opportunityreelplan",
            name="facebook_post_error",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="opportunityreellog",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("rendered", "Rendered"),
                    ("posted", "Posted"),
                    ("failed", "Failed"),
                    ("skipped", "Skipped"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
        migrations.AddIndex(
            model_name="opportunityreelplan",
            index=models.Index(
                fields=["status", "facebook_posted_at"],
                name="opportuniti_status_07da10_idx",
            ),
        ),
    ]
