# Generated by Django 6.0.6 on 2026-08-21 15:49

import hashlib
import re

import django.db.models.deletion
from django.db import migrations, models


cycle_range_re = re.compile(r"\b((?:19|20)\d{2})\s*[/\-–]\s*((?:19|20)?\d{2})\b")
year_re = re.compile(r"\b(?:19|20)\d{2}\b")


def normalize(value):
    return " ".join(str(value or "").casefold().split())


def programme_title(value):
    value = normalize(value).replace("–", "-")
    value = cycle_range_re.sub(" ", value)
    value = year_re.sub(" ", value)
    value = re.sub(r"\b(spring|summer|autumn|fall|winter)\s+(intake|entry|call)?\b", " ", value)
    value = re.sub(r"\b(intake|entry)\b", " ", value)
    value = re.sub(r"[^a-z0-9]+", " ", value)
    return " ".join(value.split())


def cycle(title, deadline):
    match = cycle_range_re.search(str(title or ""))
    if match:
        first, second = match.groups()
        if len(second) == 2:
            second = first[:2] + second
        return f"{first}/{second}"
    title_years = year_re.findall(str(title or ""))
    if title_years:
        return title_years[-1]
    return str(deadline.year) if deadline else ""


def identity(title, provider, university, country, degrees):
    parts = [
        programme_title(title),
        normalize(provider),
        normalize(university),
        normalize(country),
        "|".join(sorted(normalize(value) for value in (degrees or []))),
    ]
    return hashlib.sha256("\x1f".join(parts).encode("utf-8")).hexdigest()


def backfill_cycle_identity(apps, schema_editor):
    Opportunity = apps.get_model("opportunities", "Opportunity")
    Lead = apps.get_model("opportunities", "ScholarshipResearchLead")
    Country = apps.get_model("reference_data", "Country")
    countries = dict(Country.objects.values_list("id", "name"))

    opportunities = []
    for item in Opportunity.objects.all().iterator(chunk_size=500):
        item.application_cycle = cycle(item.title, item.deadline)
        item.identity_key = identity(
            item.title,
            item.provider_name,
            item.university_name,
            countries.get(item.country_ref_id, ""),
            item.degree_levels,
        )
        opportunities.append(item)
        if len(opportunities) == 500:
            Opportunity.objects.bulk_update(opportunities, ["application_cycle", "identity_key"])
            opportunities = []
    if opportunities:
        Opportunity.objects.bulk_update(opportunities, ["application_cycle", "identity_key"])

    leads = []
    for item in Lead.objects.all().iterator(chunk_size=500):
        item.application_cycle = cycle(item.title, item.detected_deadline)
        degrees = [item.degree_level] if item.degree_level else []
        item.identity_key = identity(
            item.title,
            item.provider_name,
            item.university,
            item.country,
            degrees,
        )
        leads.append(item)
        if len(leads) == 500:
            Lead.objects.bulk_update(leads, ["application_cycle", "identity_key"])
            leads = []
    if leads:
        Lead.objects.bulk_update(leads, ["application_cycle", "identity_key"])


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0025_opportunityreelplan_facebook_posting'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityRefreshLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_cycle', models.CharField(blank=True, db_index=True, max_length=40)),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('applied_fields', models.JSONField(blank=True, default=list)),
                ('skipped_fields', models.JSONField(blank=True, default=list)),
                ('source_url', models.URLField(max_length=2000)),
                ('evidence_text', models.TextField()),
                ('identity_confidence', models.CharField(blank=True, db_index=True, max_length=20)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('applied_by', models.CharField(default='scholarship_agent', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='opportunity',
            name='application_cycle',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='identity_key',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='scholarshipresearchlead',
            name='application_cycle',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AddField(
            model_name='scholarshipresearchlead',
            name='identity_key',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='scholarshipresearchlead',
            name='matched_opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_lead_matches', to='opportunities.opportunity'),
        ),
        migrations.AddField(
            model_name='scholarshipresearchlead',
            name='proposed_changes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='scholarshipresearchlead',
            name='refresh_applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scholarshipresearchlead',
            name='resolution',
            field=models.CharField(choices=[('new', 'New scholarship'), ('unchanged_duplicate', 'Unchanged duplicate'), ('update_existing', 'Update existing scholarship'), ('needs_review', 'Needs review')], db_index=True, default='new', max_length=40),
        ),
        migrations.AddField(
            model_name='scholarshipresearchlead',
            name='resolution_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scholarshipresearchlead',
            name='source_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_cycle_identity, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='scholarshipresearchlead',
            index=models.Index(fields=['resolution', 'review_status'], name='opportuniti_resolut_05c978_idx'),
        ),
        migrations.AddField(
            model_name='opportunityrefreshlog',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_logs', to='opportunities.opportunity'),
        ),
        migrations.AddField(
            model_name='opportunityrefreshlog',
            name='research_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refresh_logs', to='opportunities.scholarshipresearchlead'),
        ),
        migrations.AddIndex(
            model_name='opportunityrefreshlog',
            index=models.Index(fields=['opportunity', 'created_at'], name='opportuniti_opportu_c2301a_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunityrefreshlog',
            index=models.Index(fields=['application_cycle'], name='opportuniti_applica_f8527b_idx'),
        ),
    ]
