# Generated by Django 6.0.5 on 2026-08-23 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0027_classify_legacy_research_leads'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='application_fee_status',
            field=models.CharField(choices=[('unknown', 'Unknown / not stated'), ('free', 'Confirmed free'), ('paid', 'Application fee required')], default='unknown', max_length=10),
        ),
    ]
