export const PROVINCES = [
  "Punjab",
  "Sindh",
  "Khyber Pakhtunkhwa",
  "Balochistan",
  "Gilgit-Baltistan",
  "Azad Jammu and Kashmir",
  "Islamabad Capital Territory",
  "Other",
];

export const EDUCATION_LEVELS = [
  "Matric",
  "FSc",
  "A-Level",
  "DAE/Diploma",
  "Bachelor",
  "Master",
  "MS/MPhil",
  "PhD",
  "Other",
];

export const TARGET_DEGREE_LEVELS = [
  "Undergraduate",
  "Master",
  "PhD",
  "Postdoc",
  "Exchange",
  "Short Course",
  "Diploma/Certificate",
];

export const RESULT_STATUSES = [
  "Completed",
  "Final Year",
  "In Progress",
  "Waiting for Result",
  "Other",
];

export const GRADING_SYSTEMS = [
  { label: "CGPA out of 4", value: "CGPA_4" },
  { label: "CGPA out of 5", value: "CGPA_5" },
  { label: "Percentage", value: "Percentage" },
  { label: "Division", value: "Division" },
  { label: "Other", value: "Other" },
];

export const COUNTRY_REGIONS = {
  Asia: [
    "Afghanistan",
    "Bangladesh",
    "Bhutan",
    "Brunei",
    "Cambodia",
    "China",
    "Hong Kong",
    "India",
    "Indonesia",
    "Japan",
    "Kazakhstan",
    "Kyrgyzstan",
    "Laos",
    "Malaysia",
    "Maldives",
    "Mongolia",
    "Myanmar",
    "Nepal",
    "Pakistan",
    "Philippines",
    "Singapore",
    "South Korea",
    "Sri Lanka",
    "Taiwan",
    "Tajikistan",
    "Thailand",
    "Turkmenistan",
    "Uzbekistan",
    "Vietnam",
  ],
  Europe: [
    "Austria",
    "Belgium",
    "Bulgaria",
    "Croatia",
    "Cyprus",
    "Czech Republic",
    "Denmark",
    "Estonia",
    "Finland",
    "France",
    "Germany",
    "Greece",
    "Hungary",
    "Ireland",
    "Italy",
    "Latvia",
    "Lithuania",
    "Luxembourg",
    "Malta",
    "Netherlands",
    "Norway",
    "Poland",
    "Portugal",
    "Romania",
    "Slovakia",
    "Slovenia",
    "Spain",
    "Sweden",
    "Switzerland",
    "Turkey",
    "UK",
  ],
  "Middle East": [
    "Bahrain",
    "Iran",
    "Iraq",
    "Israel",
    "Jordan",
    "Kuwait",
    "Lebanon",
    "Oman",
    "Palestine",
    "Qatar",
    "Saudi Arabia",
    "Syria",
    "UAE",
    "Yemen",
  ],
  Africa: [
    "Algeria",
    "Botswana",
    "Cameroon",
    "Egypt",
    "Ethiopia",
    "Ghana",
    "Kenya",
    "Morocco",
    "Nigeria",
    "Rwanda",
    "Senegal",
    "South Africa",
    "Tanzania",
    "Tunisia",
    "Uganda",
    "Zambia",
    "Zimbabwe",
  ],
  "North America": ["Canada", "Mexico", "USA"],
  "Latin America": [
    "Argentina",
    "Brazil",
    "Chile",
    "Colombia",
    "Costa Rica",
    "Ecuador",
    "Peru",
    "Uruguay",
  ],
  Oceania: ["Australia", "Fiji", "New Zealand"],
  Other: ["Other"],
} as const;

export const COUNTRIES = Array.from(new Set(Object.values(COUNTRY_REGIONS).flat())).sort();

export const STUDY_MODE_PREFERENCES = ["On-campus", "Online", "Hybrid", "Any"];

export const FUNDING_PREFERENCES = [
  "Fully Funded Only",
  "Partial Funding Acceptable",
  "Low Tuition",
  "Self-Funded Possible",
  "Any",
];

export const APPLICATION_FEE_PREFERENCES = [
  "No Application Fee Only",
  "Low Application Fee",
  "Can Pay Application Fee",
  "Any",
];

export const LANGUAGE_INSTRUCTION_PREFERENCES = [
  "English Only",
  "Chinese Acceptable",
  "Turkish Acceptable",
  "German Acceptable",
  "Any",
];

export const DOCUMENT_OPTIONS = [
  "CNIC",
  "Domicile",
  "Passport",
  "Transcript",
  "Degree",
  "CV",
  "SOP",
  "Study Plan",
  "Recommendation Letters",
  "Research Proposal",
  "English Proficiency Certificate",
  "IELTS",
  "TOEFL",
  "Duolingo",
  "PTE",
  "HSK",
  "GRE",
  "GMAT",
  "Income Certificate",
  "Bank Statement",
  "Police Clearance",
  "Medical Certificate",
];

export const SPECIAL_SCHOLARSHIP_CATEGORIES = [
  "Women-focused scholarships",
  "Need-based scholarships",
  "Province-specific scholarships",
  "Minority/community scholarships",
  "Disability-focused scholarships",
  "Flood-affected scholarships",
  "Rural-area scholarships",
];

export const COMMON_FIELDS_OF_STUDY = [
  "Computer Science",
  "Data Science",
  "Artificial Intelligence",
  "Engineering",
  "Medical Sciences",
  "Business",
  "Social Sciences",
  "Agriculture",
  "Arts",
  "Education",
  "Environmental Sciences",
  "Law",
  "Other",
];

export const COMMON_SKILLS = [
  "Academic writing",
  "Research",
  "Data analysis",
  "Programming",
  "Teaching",
  "Leadership",
  "Communication",
  "Project management",
  "Design",
  "Microsoft Office",
  "English writing",
];
