name = "facebook-poster"
main = "src/index.js"
compatibility_date = "2026-05-25"

[triggers]
crons = ["0 9,12,15 * * *"]

[[routes]]
pattern = "facebook-poster.scholarsrepublic.org"
custom_domain = true
